"""allow duplicate category names with different parents

Revision ID: 2146e16d3ba7
Revises: 4a75b6850f9c
Create Date: 2026-03-07 03:16:02.434134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2146e16d3ba7'
down_revision = '4a75b6850f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('category_name_key'), type_='unique')
        batch_op.create_unique_constraint('_category_name_parent_uc', ['name', 'parent_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('_category_name_parent_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('category_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
