"""add binary image data columns

Revision ID: 4a75b6850f9c
Revises: cb5db5899b7c
Create Date: 2026-03-06 15:51:16.447654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a75b6850f9c'
down_revision = 'cb5db5899b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('secondary_image_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('secondary_image_data')
        batch_op.drop_column('primary_image_data')

    # ### end Alembic commands ###
